### ISSUE TITLE
Improvement: Re-work GUI to be value-based

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KazDragon/paradice9#133]
```
Based on the talks by Bjarne Stroustrup and Sean Parent at GoingNative 2013, 
changing the way that the UI is designed from being based on (shared_)pointers 
to objects will improve performance by reducing heap allocations, and also 
provide a platform for easier multithreading.

See https://parasol.tamu.edu/people/bs/622-GP/value-semantics.pdf for an 
example.
```

Original issue reported on code.google.com by `matthew....@gmail.com` on 5 Sep 2013 at 11:57
* Blocked on: #92, #95

**Comment by KazDragon** [comment]
After very long and careful consideration, this just isn't going to happen.  The event model just doesn't support it without a great deal of boilerplate for each component.  It may yet occur that the ui is extracted into another library in a similar way to Telnet++ and Terminal++, but it won't happen within Paradice.
