### ISSUE TITLE
Request: DSL for composite UI components

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KazDragon/paradice9#145]
```
It is very very wordy and complicated to generate a class for a UI component.  
While in some cases it may indeed be necessary because of unique painting 
algorithms, in many cases a new component is largely a composition of other UI 
components.

If nothing else, it would be a fine feature to be able to load a UI component's 
layout at runtime from a DSL, and then fine-tune behaviour based on that.  This 
would even allow for (at least) minor edits to layout to be performed without 
having to recompile.
```

Original issue reported on code.google.com by `matthew....@gmail.com` on 26 Feb 2014 at 8:52

**Comment by KazDragon** [comment]
Considering using the JSON for the DSL.  

As a usage example, a button is currently made up in several stages. From the inside out, we have the middle component, which is of type image, and is stored in an aligned layout so that it can be centred:

    {
        "name" : "label"
        "layout" : "aligned_layout",
        content : [
            { "name" : "image",
              "type" : "image" 
              "hint" : [ "vertical_alignment_centre",
                         "horizontal_alignment_centre" ]
            }
        ],
    }

And so on (more design to do...)

**Comment by KazDragon** [comment]
Additionally, this DSL could be used to specify component interfaces, even in fundamental objects, such as image's value property:

    {
      "name" : "image",
      "properties" : [
        { "name" : "value" }
    }

We could also augment our button class to have a signal connector called "on_click":

    {
      "name" : "button",
      "type" : "framed_component",
      "override" : [
        { "name" : "frame",
          "type" : "solid_frame"
        },
        { "name" : "label",
          "type" : "label"
        }
      ],
      "signals" : [
        { "name" : "on_click" }
      ]
    }

Some signals are parametrized, so this would have to be part of the language here:

    "signals" : [
      { "name" : "some_signal",
        "arguments" : [
          { "arg0", "string" },
          { "arg1", "int" },
          { "arg2", "button" }
        ]
      }
    ]

This will, at least, teach C++ code how to cast a particular signal in order to connect to it.

**Comment by KazDragon** [comment]
Boost.PropertyTree should make short work of this.

**Comment by KazDragon** [comment]
Requires construction of some kind of resource manager at start-up that loads a series of JSON (or other config) files into itself and can present them as a property tree.  This then provides two pieces of functionality:

* They can create their basic models via the property tree:

    model_ = create_model_from_ptree<basic_model>(ptree, "image");

* A component can be constructed using a series of overrides:

    auto im = image{image_ptree};

**Comment by KazDragon** [comment]
In the interests of uniformity, the "override"s above could be changed to "content" and "properties" where appropriate.  This would allow very similar code to work for components being default constructed and from being customized.
