### ISSUE TITLE
Improvement: Remove Guibuilder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KazDragon/paradice9#148]
```
Guibuilder is a (badly misnamed) testbed for GUI component development.  It has 
no real place in the project.

Instead, a test framework should be devised that allows for a more controlled 
and scriptable environment.
```

Original issue reported on code.google.com by `matthew....@gmail.com` on 16 Oct 2014 at 10:10

**Comment by KazDragon** [comment]
Any kind of scriptable environment would be possible after making the GUI-style DSL.  I'd consider just removing GUIBuilder wholesale, since it no longer even builds.
