### ISSUE TITLE
Dead Code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KazDragon/paradice9#149]
```
There's quite some dead code in the project, for example the NAWS client 
(Paradice has only ever been a NAWS server).  

For now, such things should be deleted.
```

Original issue reported on code.google.com by `matthew....@gmail.com` on 16 Oct 2014 at 10:11

**Comment by KazDragon** [comment]
NAWS client vanished with the integration of Telnet++.  Is there other dead code?

**Comment by KazDragon** [comment]
Lots of dead code gone with Telnet++/Terminal++ integration.  I
m considering this as done.
